name: task-a cd

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt
      - name: Run tests
        run: |
          pytest ./task_a/task_a.py
